
services:
  cache-test:
    hostname: cache-test
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ./cache:/data
    
    networks:
      - jobboard-network
  

  elasticsearch-test:
    container_name: elastic-test
    image: elasticsearch
    build:
      context: ./elasticsearch
      dockerfile: ./Dockerfile
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    networks:
      - elastic
    volumes:
      - ./elasticsearch/localdata1/opt/elastic:/usr/share/elasticsearch/data


  jobboard-test:
    container_name: jobboard-test
    build:
      context: jobboard
    ports:
      - "8000:8000"
    volumes:
      - ./jobboard:/app
    networks:
      - jobboard-network
      
    environment:
      # set environment variables
      - CACHE_PORT=${CACHE_PORT:-6379}
      - CACHE_HOST=${CACHE_HOST:-cache}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ELASTIC_PORT=${ELASTIC_PORT:-9200}
      - ELASTIC_HOST=${ELASTIC_HOST:-elasticsearch}
      - JOB_API_KEY=${JOB_API_KEY}
    command: gunicorn -c ./server/gunicorn.conf.py manage:app
    depends_on:
      - elasticsearch
  
  worker-test:
    container_name: worker-test
    build:
      context: jobboard
    ports:
      - "8020:5555"
    volumes:
      - ./jobboard:/app
    command: ["honcho", "start"] 
    environment:
      # set environment variables
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ELASTIC_PORT=${ELASTIC_PORT:-9200}
      - ELASTIC_HOST=${ELASTIC_HOST:-elasticsearch}
      - CACHE_PORT=${CACHE_PORT:-6379}
      - CACHE_HOST=${CACHE_HOST:-cache}
      - JOB_API_KEY=${JOB_API_KEY}
    depends_on:
      - elasticsearch
      - cache
    networks:
      - jobboard-network


networks:
  elastic:
    external:
      name: jobboard-network