services:
  cache:
    hostname: cache
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ./cache:/data

  elasticsearch:
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    volumes:
      - ./elasticsearch/localdata/certs:/usr/share/elasticsearch/config/certs
      - ./elasticsearch/localdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME:-elastic}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.license.self_generated.type=${LICENSE}
    mem_limit: 2147483648
    cap_add: 
      - SYS_RESOURCE  # Add this to give more capabilities
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  jobboard:
    container_name: jobboard
    build:
      context: jobboard
    ports:
      - "8000:8000"
    volumes:
      - ./jobboard:/app
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ELASTIC_PORT=${ELASTIC_PORT:-9200}
      - CACHE_PORT=${CACHE_PORT:-6379}
      - CACHE_HOST=${CACHE_HOST:-cache}
      - ELASTIC_HOST=${ELASTIC_HOST:-elasticsearch}
      - JOB_API_KEY=${JOB_API_KEY}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME:-elastic}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    command: fastapi dev manage.py --host=0.0.0.0
    depends_on:
      - elasticsearch

  worker:
    container_name: worker
    build:
      context: jobboard
    ports:
      - "8020:5555"
    volumes:
      - ./jobboard:/app
    command: ["honcho", "start"]
    environment:
      - CACHE_URL=redis://cache:6379/0
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ELASTIC_PORT=${ELASTIC_PORT:-9200}
      - ELASTIC_HOST=${ELASTIC_HOST:-elasticsearch}
      - CACHE_PORT=${CACHE_PORT:-6379}
      - CACHE_HOST=${CACHE_HOST:-cache}
      - JOB_API_KEY=${JOB_API_KEY}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME:-elastic}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
      - elasticsearch
      - cache

networks:
  elastic:
    external:
      name: jobboard-network
